server:
  port: 8100



eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8100/eureka
    register-with-eureka: false
    fetch-registry: false
spring:
  security:
    user:
      name: pppoa
      password: pppoa